//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b17-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.28 at 08:29:20 PM CEST 
//


package org.doe4ejb3.jaxb.persistence;

import javax.xml.bind.annotation.XmlRegistry;
import org.doe4ejb3.jaxb.persistence.Persistence.PersistenceUnit;
import org.doe4ejb3.jaxb.persistence.Persistence.PersistenceUnit.Properties;
import org.doe4ejb3.jaxb.persistence.Persistence.PersistenceUnit.Properties.Property;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.doe4ejb3.jaxb.persistence package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.doe4ejb3.jaxb.persistence
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersistenceUnit }
     * 
     */
    public PersistenceUnit createPersistencePersistenceUnit() {
        return new PersistenceUnit();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createPersistencePersistenceUnitPropertiesProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Persistence }
     * 
     */
    public Persistence createPersistence() {
        return new Persistence();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createPersistencePersistenceUnitProperties() {
        return new Properties();
    }

}
