//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b17-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.28 at 08:29:25 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hooksType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hooksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="menu-hook" type="{http://jcp.org/jsr/198/extension-manifest}menuHookType" minOccurs="0"/>
 *         &lt;element name="document-hook" type="{http://jcp.org/jsr/198/extension-manifest}documentHookType" minOccurs="0"/>
 *         &lt;element name="ide-listener-hook" type="{http://jcp.org/jsr/198/extension-manifest}ideListenerHookType" minOccurs="0"/>
 *         &lt;element name="editor-hook" type="{http://jcp.org/jsr/198/extension-manifest}editorHookType" minOccurs="0"/>
 *         &lt;element name="property-hook" type="{http://jcp.org/jsr/198/extension-manifest}propertyHookType" minOccurs="0"/>
 *         &lt;element name="log-hook" type="{http://jcp.org/jsr/198/extension-manifest}logHookType" minOccurs="0"/>
 *         &lt;element name="wizard-hook" type="{http://jcp.org/jsr/198/extension-manifest}wizardHookType" minOccurs="0"/>
 *         &lt;element name="build-system-hook" type="{http://jcp.org/jsr/198/extension-manifest}buildSystemHookType" minOccurs="0"/>
 *         &lt;element name="feature-hook" type="{http://jcp.org/jsr/198/extension-manifest}featureHookType" minOccurs="0"/>
 *         &lt;element name="hook-handler-hook" type="{http://jcp.org/jsr/198/extension-manifest}hookHandlerHookType" minOccurs="0"/>
 *         &lt;element name="vfs-hook" type="{http://jcp.org/jsr/198/extension-manifest}vfsHookType" minOccurs="0"/>
 *         &lt;element ref="{http://jcp.org/jsr/198/extension-manifest}custom-hook" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hooksType", propOrder = {
    "menuHookOrDocumentHookOrIdeListenerHook"
})
public class HooksType {

    @XmlElements({
        @XmlElement(name = "property-hook", required = true, type = PropertyHookType.class),
        @XmlElement(name = "ide-listener-hook", required = true, type = IdeListenerHookType.class),
        @XmlElement(name = "build-system-hook", required = true, type = BuildSystemHookType.class),
        @XmlElement(name = "wizard-hook", required = true, type = WizardHookType.class),
        @XmlElement(name = "custom-hook", required = true, type = CustomHookType.class),
        @XmlElement(name = "log-hook", required = true, type = LogHookType.class),
        @XmlElement(name = "document-hook", required = true, type = DocumentHookType.class),
        @XmlElement(name = "vfs-hook", required = true, type = VfsHookType.class),
        @XmlElement(name = "feature-hook", required = true, type = FeatureHookType.class),
        @XmlElement(name = "hook-handler-hook", required = true, type = HookHandlerHookType.class),
        @XmlElement(name = "menu-hook", required = true, type = MenuHookType.class),
        @XmlElement(name = "editor-hook", required = true, type = EditorHookType.class)
    })
    protected List<Object> menuHookOrDocumentHookOrIdeListenerHook;

    /**
     * Gets the value of the menuHookOrDocumentHookOrIdeListenerHook property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menuHookOrDocumentHookOrIdeListenerHook property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenuHookOrDocumentHookOrIdeListenerHook().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyHookType }
     * {@link IdeListenerHookType }
     * {@link BuildSystemHookType }
     * {@link WizardHookType }
     * {@link CustomHookType }
     * {@link LogHookType }
     * {@link DocumentHookType }
     * {@link VfsHookType }
     * {@link FeatureHookType }
     * {@link HookHandlerHookType }
     * {@link MenuHookType }
     * {@link EditorHookType }
     * 
     * 
     */
    public List<Object> getMenuHookOrDocumentHookOrIdeListenerHook() {
        if (menuHookOrDocumentHookOrIdeListenerHook == null) {
            menuHookOrDocumentHookOrIdeListenerHook = new ArrayList<Object>();
        }
        return this.menuHookOrDocumentHookOrIdeListenerHook;
    }

}
