//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b17-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.28 at 08:29:25 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jcp.org/jsr/198/extension-manifest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.doe4ejb3.jaxb.plugin;
