//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.11 at 07:02:52 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recognizersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recognizersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="by-suffix" type="{http://jcp.org/jsr/198/extension-manifest}suffixRecognizerType" maxOccurs="unbounded"/>
 *         &lt;element name="by-xml-root" type="{http://jcp.org/jsr/198/extension-manifest}xmlRootDocumentType" maxOccurs="unbounded"/>
 *         &lt;element name="by-xml-doctype" type="{http://jcp.org/jsr/198/extension-manifest}xmlDocType" maxOccurs="unbounded"/>
 *         &lt;element name="by-recognizer" type="{http://jcp.org/jsr/198/extension-manifest}customRecognizerType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recognizersType", propOrder = {
    "bySuffixOrByXmlRootOrByXmlDoctype"
})
public class RecognizersType {

    @XmlElements({
        @XmlElement(name = "by-xml-root", type = XmlRootDocumentType.class),
        @XmlElement(name = "by-recognizer", type = CustomRecognizerType.class),
        @XmlElement(name = "by-xml-doctype", type = XmlDocType.class),
        @XmlElement(name = "by-suffix", type = SuffixRecognizerType.class)
    })
    protected List<Object> bySuffixOrByXmlRootOrByXmlDoctype;

    /**
     * Gets the value of the bySuffixOrByXmlRootOrByXmlDoctype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bySuffixOrByXmlRootOrByXmlDoctype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBySuffixOrByXmlRootOrByXmlDoctype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlRootDocumentType }
     * {@link CustomRecognizerType }
     * {@link XmlDocType }
     * {@link SuffixRecognizerType }
     * 
     * 
     */
    public List<Object> getBySuffixOrByXmlRootOrByXmlDoctype() {
        if (bySuffixOrByXmlRootOrByXmlDoctype == null) {
            bySuffixOrByXmlRootOrByXmlDoctype = new ArrayList<Object>();
        }
        return this.bySuffixOrByXmlRootOrByXmlDoctype;
    }

}
