//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.11 at 07:02:52 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for wizardsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wizardsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wizard-category" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}identifiableType">
 *                 &lt;sequence>
 *                   &lt;element name="label" type="{http://jcp.org/jsr/198/extension-manifest}i18n_string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="parent-category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="wizard" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}wizardType">
 *                 &lt;attribute name="category-ref" type="{http://jcp.org/jsr/198/extension-manifest}className" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wizardsType", propOrder = {
    "wizardCategory",
    "wizard"
})
public class WizardsType {

    @XmlElement(name = "wizard-category")
    protected List<WizardsType.WizardCategory> wizardCategory;
    @XmlElement(required = true)
    protected List<WizardsType.Wizard> wizard;

    /**
     * Gets the value of the wizardCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wizardCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWizardCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WizardsType.WizardCategory }
     * 
     * 
     */
    public List<WizardsType.WizardCategory> getWizardCategory() {
        if (wizardCategory == null) {
            wizardCategory = new ArrayList<WizardsType.WizardCategory>();
        }
        return this.wizardCategory;
    }

    /**
     * Gets the value of the wizard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wizard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWizard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WizardsType.Wizard }
     * 
     * 
     */
    public List<WizardsType.Wizard> getWizard() {
        if (wizard == null) {
            wizard = new ArrayList<WizardsType.Wizard>();
        }
        return this.wizard;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}wizardType">
     *       &lt;attribute name="category-ref" type="{http://jcp.org/jsr/198/extension-manifest}className" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Wizard
        extends WizardType
    {

        @XmlAttribute(name = "category-ref")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String categoryRef;

        /**
         * Gets the value of the categoryRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryRef() {
            return categoryRef;
        }

        /**
         * Sets the value of the categoryRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryRef(String value) {
            this.categoryRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}identifiableType">
     *       &lt;sequence>
     *         &lt;element name="label" type="{http://jcp.org/jsr/198/extension-manifest}i18n_string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="parent-category" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "label"
    })
    public static class WizardCategory
        extends IdentifiableType
    {

        @XmlElement(required = true)
        protected I18NString label;
        @XmlAttribute(name = "parent-category")
        protected String parentCategory;

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link I18NString }
         *     
         */
        public I18NString getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link I18NString }
         *     
         */
        public void setLabel(I18NString value) {
            this.label = value;
        }

        /**
         * Gets the value of the parentCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentCategory() {
            return parentCategory;
        }

        /**
         * Sets the value of the parentCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentCategory(String value) {
            this.parentCategory = value;
        }

    }

}
