//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b17-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.28 at 08:29:25 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.doe4ejb3.jaxb.plugin.MenuHookType.ItemFactories;


/**
 * <p>Java class for menuHookType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="menuHookType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}hookType">
 *       &lt;all>
 *         &lt;element name="actions" type="{http://jcp.org/jsr/198/extension-manifest}actionsType" minOccurs="0"/>
 *         &lt;element name="menus" type="{http://jcp.org/jsr/198/extension-manifest}menusType" minOccurs="0"/>
 *         &lt;element name="toolbars" type="{http://jcp.org/jsr/198/extension-manifest}toolbarsType" minOccurs="0"/>
 *         &lt;element name="item-factories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item-factory-class" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "menuHookType", propOrder = {
    "actions",
    "menus",
    "toolbars",
    "itemFactories"
})
public class MenuHookType
    extends HookType
{

    protected ActionsType actions;
    protected MenusType menus;
    protected ToolbarsType toolbars;
    @XmlElement(name = "item-factories")
    protected ItemFactories itemFactories;

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionsType }
     *     
     */
    public ActionsType getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionsType }
     *     
     */
    public void setActions(ActionsType value) {
        this.actions = value;
    }

    /**
     * Gets the value of the menus property.
     * 
     * @return
     *     possible object is
     *     {@link MenusType }
     *     
     */
    public MenusType getMenus() {
        return menus;
    }

    /**
     * Sets the value of the menus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenusType }
     *     
     */
    public void setMenus(MenusType value) {
        this.menus = value;
    }

    /**
     * Gets the value of the toolbars property.
     * 
     * @return
     *     possible object is
     *     {@link ToolbarsType }
     *     
     */
    public ToolbarsType getToolbars() {
        return toolbars;
    }

    /**
     * Sets the value of the toolbars property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolbarsType }
     *     
     */
    public void setToolbars(ToolbarsType value) {
        this.toolbars = value;
    }

    /**
     * Gets the value of the itemFactories property.
     * 
     * @return
     *     possible object is
     *     {@link ItemFactories }
     *     
     */
    public ItemFactories getItemFactories() {
        return itemFactories;
    }

    /**
     * Sets the value of the itemFactories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemFactories }
     *     
     */
    public void setItemFactories(ItemFactories value) {
        this.itemFactories = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item-factory-class" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemFactoryClass"
    })
    public static class ItemFactories {

        @XmlElement(name = "item-factory-class", required = true)
        protected List<Object> itemFactoryClass;

        /**
         * Gets the value of the itemFactoryClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the itemFactoryClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItemFactoryClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getItemFactoryClass() {
            if (itemFactoryClass == null) {
                itemFactoryClass = new ArrayList<Object>();
            }
            return this.itemFactoryClass;
        }

    }

}
