//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b17-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.28 at 08:29:25 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for buildSystemHookType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="buildSystemHookType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}hookType">
 *       &lt;all>
 *         &lt;element name="build-listeners" type="{http://jcp.org/jsr/198/extension-manifest}ideListenersType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buildSystemHookType", propOrder = {
    "buildListeners"
})
public class BuildSystemHookType
    extends HookType
{

    @XmlElement(name = "build-listeners")
    protected IdeListenersType buildListeners;

    /**
     * Gets the value of the buildListeners property.
     * 
     * @return
     *     possible object is
     *     {@link IdeListenersType }
     *     
     */
    public IdeListenersType getBuildListeners() {
        return buildListeners;
    }

    /**
     * Sets the value of the buildListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdeListenersType }
     *     
     */
    public void setBuildListeners(IdeListenersType value) {
        this.buildListeners = value;
    }

}
