//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.11 at 07:02:52 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for editorHookType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="editorHookType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}hookType">
 *       &lt;all>
 *         &lt;element name="editors" type="{http://jcp.org/jsr/198/extension-manifest}editorsType" minOccurs="0"/>
 *         &lt;element name="mappings" type="{http://jcp.org/jsr/198/extension-manifest}mappingsType" minOccurs="0"/>
 *         &lt;element name="editor-listeners" type="{http://jcp.org/jsr/198/extension-manifest}editorListenersType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "editorHookType", propOrder = {
    "editors",
    "mappings",
    "editorListeners"
})
public class EditorHookType
    extends HookType
{

    protected EditorsType editors;
    protected MappingsType mappings;
    @XmlElement(name = "editor-listeners")
    protected EditorListenersType editorListeners;

    /**
     * Gets the value of the editors property.
     * 
     * @return
     *     possible object is
     *     {@link EditorsType }
     *     
     */
    public EditorsType getEditors() {
        return editors;
    }

    /**
     * Sets the value of the editors property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditorsType }
     *     
     */
    public void setEditors(EditorsType value) {
        this.editors = value;
    }

    /**
     * Gets the value of the mappings property.
     * 
     * @return
     *     possible object is
     *     {@link MappingsType }
     *     
     */
    public MappingsType getMappings() {
        return mappings;
    }

    /**
     * Sets the value of the mappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingsType }
     *     
     */
    public void setMappings(MappingsType value) {
        this.mappings = value;
    }

    /**
     * Gets the value of the editorListeners property.
     * 
     * @return
     *     possible object is
     *     {@link EditorListenersType }
     *     
     */
    public EditorListenersType getEditorListeners() {
        return editorListeners;
    }

    /**
     * Sets the value of the editorListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditorListenersType }
     *     
     */
    public void setEditorListeners(EditorListenersType value) {
        this.editorListeners = value;
    }

}
