//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.11 at 07:02:52 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logHookType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logHookType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}hookType">
 *       &lt;all>
 *         &lt;element name="log-pages" type="{http://jcp.org/jsr/198/extension-manifest}logPagesType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logHookType", propOrder = {
    "logPages"
})
public class LogHookType
    extends HookType
{

    @XmlElement(name = "log-pages")
    protected LogPagesType logPages;

    /**
     * Gets the value of the logPages property.
     * 
     * @return
     *     possible object is
     *     {@link LogPagesType }
     *     
     */
    public LogPagesType getLogPages() {
        return logPages;
    }

    /**
     * Sets the value of the logPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogPagesType }
     *     
     */
    public void setLogPages(LogPagesType value) {
        this.logPages = value;
    }

}
