//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.11 at 07:02:52 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wizardHookType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wizardHookType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}hookType">
 *       &lt;all>
 *         &lt;element name="wizards" type="{http://jcp.org/jsr/198/extension-manifest}wizardsType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wizardHookType", propOrder = {
    "wizards"
})
public class WizardHookType
    extends HookType
{

    protected WizardsType wizards;

    /**
     * Gets the value of the wizards property.
     * 
     * @return
     *     possible object is
     *     {@link WizardsType }
     *     
     */
    public WizardsType getWizards() {
        return wizards;
    }

    /**
     * Sets the value of the wizards property.
     * 
     * @param value
     *     allowed object is
     *     {@link WizardsType }
     *     
     */
    public void setWizards(WizardsType value) {
        this.wizards = value;
    }

}
