//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b17-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.28 at 08:29:25 PM CEST 
//


package org.doe4ejb3.jaxb.plugin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for actionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://jcp.org/jsr/198/extension-manifest}identifiableType">
 *       &lt;all>
 *         &lt;element name="label" type="{http://jcp.org/jsr/198/extension-manifest}i18n_string"/>
 *         &lt;element name="mnemonic" type="{http://jcp.org/jsr/198/extension-manifest}i18n_char" minOccurs="0"/>
 *         &lt;element name="tooltip" type="{http://jcp.org/jsr/198/extension-manifest}i18n_string" minOccurs="0"/>
 *         &lt;element name="iconpath" type="{http://jcp.org/jsr/198/extension-manifest}i18n_string" minOccurs="0"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="checked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="invoke-class" type="{http://jcp.org/jsr/198/extension-manifest}className" minOccurs="0"/>
 *         &lt;element name="update-class" type="{http://jcp.org/jsr/198/extension-manifest}className" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="toggle" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actionType", propOrder = {
    "label",
    "mnemonic",
    "tooltip",
    "iconpath",
    "enabled",
    "checked",
    "invokeClass",
    "updateClass"
})
public class ActionType
    extends IdentifiableType
{

    @XmlElement(required = true)
    protected I18NString label;
    protected I18NChar mnemonic;
    protected I18NString tooltip;
    protected I18NString iconpath;
    protected Boolean enabled;
    protected Boolean checked;
    @XmlElement(name = "invoke-class")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String invokeClass;
    @XmlElement(name = "update-class")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String updateClass;
    @XmlAttribute
    protected Boolean toggle;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link I18NString }
     *     
     */
    public I18NString getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link I18NString }
     *     
     */
    public void setLabel(I18NString value) {
        this.label = value;
    }

    /**
     * Gets the value of the mnemonic property.
     * 
     * @return
     *     possible object is
     *     {@link I18NChar }
     *     
     */
    public I18NChar getMnemonic() {
        return mnemonic;
    }

    /**
     * Sets the value of the mnemonic property.
     * 
     * @param value
     *     allowed object is
     *     {@link I18NChar }
     *     
     */
    public void setMnemonic(I18NChar value) {
        this.mnemonic = value;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link I18NString }
     *     
     */
    public I18NString getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link I18NString }
     *     
     */
    public void setTooltip(I18NString value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the iconpath property.
     * 
     * @return
     *     possible object is
     *     {@link I18NString }
     *     
     */
    public I18NString getIconpath() {
        return iconpath;
    }

    /**
     * Sets the value of the iconpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link I18NString }
     *     
     */
    public void setIconpath(I18NString value) {
        this.iconpath = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the checked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChecked() {
        return checked;
    }

    /**
     * Sets the value of the checked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChecked(Boolean value) {
        this.checked = value;
    }

    /**
     * Gets the value of the invokeClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvokeClass() {
        return invokeClass;
    }

    /**
     * Sets the value of the invokeClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvokeClass(String value) {
        this.invokeClass = value;
    }

    /**
     * Gets the value of the updateClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateClass() {
        return updateClass;
    }

    /**
     * Sets the value of the updateClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateClass(String value) {
        this.updateClass = value;
    }

    /**
     * Gets the value of the toggle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToggle() {
        return toggle;
    }

    /**
     * Sets the value of the toggle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToggle(Boolean value) {
        this.toggle = value;
    }

}
